# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlasmap < Formula
  desc "Network topology discovery from the inside of a host"
  homepage "https://tools.hostatlas.app"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostatlas-labs/atlasmap/releases/download/v1.0.0/atlasmap_1.0.0_darwin_amd64.tar.gz"
      sha256 "39560c37ceab3818cad66ff5bf855ebbdc0a6607b9a85393b1d311a3ae874294"

      define_method(:install) do
        bin.install "atlasmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostatlas-labs/atlasmap/releases/download/v1.0.0/atlasmap_1.0.0_darwin_arm64.tar.gz"
      sha256 "6f13a06196080975224520c64951b8ba126760fb06d8c6c2110d9ad23bd7ff54"

      define_method(:install) do
        bin.install "atlasmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostatlas-labs/atlasmap/releases/download/v1.0.0/atlasmap_1.0.0_linux_amd64.tar.gz"
      sha256 "403fd40e82e712939a3539041a01cd948d88a691cc446444bbffe8626a004589"
      define_method(:install) do
        bin.install "atlasmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostatlas-labs/atlasmap/releases/download/v1.0.0/atlasmap_1.0.0_linux_arm64.tar.gz"
      sha256 "1aa9daf439fdbb746c41ab7e923726285d52e2b260fa23150897d3f421d32fbf"
      define_method(:install) do
        bin.install "atlasmap"
      end
    end
  end

  test do
    system "#{bin}/atlasmap", "--version"
  end
end
