# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockertop < Formula
  desc "Prettier docker stats for the terminal — CPU sparklines, Compose grouping"
  homepage "https://tools.hostatlas.app"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostatlas-labs/dockertop/releases/download/v1.0.0/dockertop_1.0.0_darwin_amd64.tar.gz"
      sha256 "40e7de08773a852a39fcceb53ba25d8504a55e1ec5fa12799ed68ee7f369c741"

      define_method(:install) do
        bin.install "dockertop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostatlas-labs/dockertop/releases/download/v1.0.0/dockertop_1.0.0_darwin_arm64.tar.gz"
      sha256 "d949c43541c2fc4ee137604dbf0ea678d574cfef812e1aab8781f16e5ce4d468"

      define_method(:install) do
        bin.install "dockertop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostatlas-labs/dockertop/releases/download/v1.0.0/dockertop_1.0.0_linux_amd64.tar.gz"
      sha256 "1682e9562067db8d9cc78e60c55ef3e3c7a3ab296e266f9467b0c8f784c751c1"
      define_method(:install) do
        bin.install "dockertop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostatlas-labs/dockertop/releases/download/v1.0.0/dockertop_1.0.0_linux_arm64.tar.gz"
      sha256 "08aaf59438cf35117f5d4f92eee2dc485053ebcba158cb8be0ff51da16f5d56b"
      define_method(:install) do
        bin.install "dockertop"
      end
    end
  end

  test do
    system "#{bin}/dockertop", "--version"
  end
end
