# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portwatch < Formula
  desc "Open port change detector with multi-channel alerts"
  homepage "https://tools.hostatlas.app"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostatlas-labs/portwatch/releases/download/v1.0.0/portwatch_1.0.0_darwin_amd64.tar.gz"
      sha256 "c713b5847f5b4a7b2907050ec0d72177d1acb2006503f0efb9d9d9578c80eb77"

      define_method(:install) do
        bin.install "portwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostatlas-labs/portwatch/releases/download/v1.0.0/portwatch_1.0.0_darwin_arm64.tar.gz"
      sha256 "c0cb54540feb6a086682f0f3269aa90677d4cdc86dd2c7e2a39a3cbaa7fcfc3a"

      define_method(:install) do
        bin.install "portwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostatlas-labs/portwatch/releases/download/v1.0.0/portwatch_1.0.0_linux_amd64.tar.gz"
      sha256 "2403d0dd80708020728a115d013ca7d3e4d00fd4abc344389c60164ecdd10997"
      define_method(:install) do
        bin.install "portwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostatlas-labs/portwatch/releases/download/v1.0.0/portwatch_1.0.0_linux_arm64.tar.gz"
      sha256 "8096ca95a43ccadc35c38a0d3dd0d0c283775959e17dfba7f9d07db811eef67a"
      define_method(:install) do
        bin.install "portwatch"
      end
    end
  end

  test do
    system "#{bin}/portwatch", "--version"
  end
end
