# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sentinel < Formula
  desc "Lightweight SSH & login attack alerter daemon"
  homepage "https://tools.hostatlas.app"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostatlas-labs/sentinel/releases/download/v1.0.0/sentinel_1.0.0_darwin_amd64.tar.gz"
      sha256 "e32445f9a8b6d4fa04090c1dea9cf01338a533e5d51aae7c4987c9e44b74b6b9"

      define_method(:install) do
        bin.install "sentinel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostatlas-labs/sentinel/releases/download/v1.0.0/sentinel_1.0.0_darwin_arm64.tar.gz"
      sha256 "8a68dd7df424e0f7e25fb6642ef2b95882ed676bef52c6eafbe2e9d5a59d2997"

      define_method(:install) do
        bin.install "sentinel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostatlas-labs/sentinel/releases/download/v1.0.0/sentinel_1.0.0_linux_amd64.tar.gz"
      sha256 "307218193a26069c10a5de0c3f765584ad35f5a06cc13be628d4cdea12aa3b42"
      define_method(:install) do
        bin.install "sentinel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostatlas-labs/sentinel/releases/download/v1.0.0/sentinel_1.0.0_linux_arm64.tar.gz"
      sha256 "9cf1c4f6e4250edc4c7b60a31aa74d9efb4d14113e79fb184f32d96639f04ed3"
      define_method(:install) do
        bin.install "sentinel"
      end
    end
  end

  test do
    system "#{bin}/sentinel", "--version"
  end
end
